services:
  caddy:
    image: caddy:latest
    network_mode: host
    container_name: caddy_server
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config: